name: Bias Testing Tests

on:
  workflow_dispatch:
    inputs:
      agent_name:
        description: "Select the agent name to run tests for"
        required: false
        type: choice
        options:
          - feedback
          - health
          - hold_code
          - ndb
          - nppes
          - preprompt

jobs:
  test:
    runs-on: uhg-runner

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.13"

    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest pytest-cov pytest-playwright pytest-html
        pip install requests

    - name: Install Playwright browsers
      run: |
        playwright install --with-deps chromium

    - name: Run bias tests for all agents
      run: |
        echo "Running tests for agent: ${{ inputs.agent_name }}"
        TEST_PATH="biastests/${{inputs.agent_name}}"
        if [ -d "$TEST_PATH" ]; then
          python -m pytest "$TEST_PATH" --html=biastests/report1.html --self-contained-html
        else
          echo "Test directory for agent ${{ inputs.agent_name }} does not exist. Skipping..."
        fi

    # - name: Upload Playwright traces
    #   uses: actions/upload-artifact@v4
    #   if: ${{ !cancelled() }}
    #   with:
    #     name: playwright-traces
    #     path: biastests/report1.html
      # Step 8: Upload dynamically generated CSV as an artifact
    - name: Upload Mismatch CSV
      uses: actions/upload-artifact@v4
      if: ${{ !cancelled() }}
      with:
        name: mismatch-csv
        path: biastests/*_holdcodecheck_mismatch.csv

    
    - name: Upload BiasTests HTML report  
      uses: actions/upload-artifact@v4  
      if: ${{ !cancelled() }}  
      with:  
        name: biastests-html-report  
        path: biastests/report1.html
